version: '3.8'
name: book_management
services:
  postgres:
    image: postgres:14
    container_name: book_management_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: