import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

// Generate TypeScript types
const types = `
// Generated by generate-typings.ts
// DO NOT EDIT THIS FILE

export interface Author {
  id: string;
  name: string;
  email: string;
  books?: Book[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Book {
  id: string;
  title: string;
  description?: string;
  publishedAt: Date;
  author: Author;
  authorId: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateAuthorInput {
  name: string;
  email: string;
}

export interface UpdateAuthorInput {
  name?: string;
  email?: string;
}

export interface CreateBookInput {
  title: string;
  description?: string;
  publishedAt: Date;
  authorId: string;
}

export interface UpdateBookInput {
  title?: string;
  description?: string;
  publishedAt?: Date;
  authorId?: string;
}
`;

// Write types to file
writeFileSync(join(__dirname, 'graphql.ts'), types);

console.log('TypeScript types generated successfully!'); 